'use strict';

/**
 * Centralized SQL queries for the Allways Show de Premios application.
 * All table names use ALLWAYS_ prefix matching Oracle 19C schema.
 * All queries use bind parameters to prevent SQL injection.
 */

// ============================================================
// ALLWAYS_PARTICIPANTES
// ============================================================

const PARTICIPANTE_INSERT = `
  INSERT INTO ALLWAYS_PARTICIPANTES (
    NOMBRE, CEDULA, TELEFONO, EMAIL, CIUDAD, DEPARTAMENTO
  ) VALUES (
    :nombre, :cedula, :telefono, :email, :ciudad, :departamento
  ) RETURNING ID INTO :id
`;

const PARTICIPANTE_FIND_BY_CEDULA = `
  SELECT ID, NOMBRE, CEDULA, TELEFONO, EMAIL,
         CIUDAD, DEPARTAMENTO, FECHA_REGISTRO, ACTIVO
  FROM ALLWAYS_PARTICIPANTES
  WHERE CEDULA = :cedula
`;

const PARTICIPANTE_FIND_BY_ID = `
  SELECT ID, NOMBRE, CEDULA, TELEFONO, EMAIL,
         CIUDAD, DEPARTAMENTO, FECHA_REGISTRO, ACTIVO
  FROM ALLWAYS_PARTICIPANTES
  WHERE ID = :id
`;

const PARTICIPANTE_LIST = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD, P.FECHA_REGISTRO,
         COUNT(DISTINCT R.ID) AS TOTAL_REGISTROS,
         COUNT(DISTINCT C.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_REGISTROS R ON R.PARTICIPANTE_ID = P.ID
  LEFT JOIN ALLWAYS_CUPONES C ON C.PARTICIPANTE_ID = P.ID
  WHERE 1=1
`;

const PARTICIPANTE_LIST_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_PARTICIPANTES
  WHERE 1=1
`;

const PARTICIPANTE_DETAIL = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD, P.FECHA_REGISTRO, P.ACTIVO
  FROM ALLWAYS_PARTICIPANTES P
  WHERE P.ID = :id
`;

const PARTICIPANTE_REGISTROS = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.IMAGEN_FACTURA, R.IMAGEN_PRODUCTOS,
         R.MOTIVO_RECHAZO, R.FECHA_VALIDACION
  FROM ALLWAYS_REGISTROS R
  WHERE R.PARTICIPANTE_ID = :participanteId
  ORDER BY R.FECHA_REGISTRO DESC
`;

// ============================================================
// ALLWAYS_REGISTROS
// ============================================================

const REGISTRO_INSERT = `
  INSERT INTO ALLWAYS_REGISTROS (
    PARTICIPANTE_ID, NUMERO_FACTURA, CANTIDAD_PRODUCTOS,
    IMAGEN_FACTURA, IMAGEN_PRODUCTOS, ESTADO, IP_REGISTRO
  ) VALUES (
    :participanteId, :numeroFactura, :cantidadProductos,
    :imagenFactura, :imagenProductos, 'PENDIENTE', :ipRegistro
  ) RETURNING ID INTO :id
`;

const REGISTRO_FIND_BY_ID = `
  SELECT R.ID, R.PARTICIPANTE_ID, R.NUMERO_FACTURA,
         R.CANTIDAD_PRODUCTOS, R.IMAGEN_FACTURA, R.IMAGEN_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         R.VALIDADO_POR, R.MOTIVO_RECHAZO, R.IP_REGISTRO,
         P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  WHERE R.ID = :id
`;

const REGISTRO_LIST = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         P.NOMBRE, P.CEDULA, P.TELEFONO
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  WHERE 1=1
`;

const REGISTRO_LIST_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  WHERE 1=1
`;

const REGISTRO_UPDATE_ESTADO = `
  UPDATE ALLWAYS_REGISTROS SET
    ESTADO = :estado,
    FECHA_VALIDACION = CURRENT_TIMESTAMP,
    VALIDADO_POR = :validadoPor,
    MOTIVO_RECHAZO = :motivoRechazo
  WHERE ID = :id
`;

// ============================================================
// ALLWAYS_CUPONES
// ============================================================

const CUPON_INSERT = `
  INSERT INTO ALLWAYS_CUPONES (
    REGISTRO_ID, PARTICIPANTE_ID, NUMERO_CUPON, MES_SORTEO
  ) VALUES (
    :registroId, :participanteId, :numeroCupon, :mesSorteo
  )
`;

const CUPON_FIND_BY_CODIGO = `
  SELECT ID, NUMERO_CUPON, REGISTRO_ID, PARTICIPANTE_ID, MES_SORTEO, FECHA_GENERACION
  FROM ALLWAYS_CUPONES
  WHERE NUMERO_CUPON = :numeroCupon
`;

const CUPON_LIST_BY_CEDULA = `
  SELECT C.ID, C.NUMERO_CUPON, C.MES_SORTEO, C.FECHA_GENERACION, C.GANADOR,
         R.NUMERO_FACTURA, R.ESTADO AS ESTADO_REGISTRO
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  WHERE P.CEDULA = :cedula
  ORDER BY C.FECHA_GENERACION DESC
`;

const CUPON_LIST_BY_REGISTRO = `
  SELECT ID, NUMERO_CUPON, MES_SORTEO, FECHA_GENERACION, GANADOR
  FROM ALLWAYS_CUPONES
  WHERE REGISTRO_ID = :registroId
  ORDER BY FECHA_GENERACION DESC
`;

const CUPON_LIST_ALL = `
  SELECT C.ID, C.NUMERO_CUPON, C.MES_SORTEO, C.FECHA_GENERACION, C.GANADOR,
         P.NOMBRE, P.CEDULA,
         R.NUMERO_FACTURA
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  WHERE 1=1
`;

const CUPON_LIST_ALL_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  WHERE 1=1
`;

// ============================================================
// ALLWAYS_PREMIOS
// ============================================================

const PREMIO_LIST = `
  SELECT ID, MES, DESCRIPCION, IMAGEN, CUPON_GANADOR_ID, FECHA_SORTEO, ACTIVO
  FROM ALLWAYS_PREMIOS
  WHERE ACTIVO = 'S'
  ORDER BY ID ASC
`;

// ============================================================
// ALLWAYS_ADMIN
// ============================================================

const ADMIN_FIND_BY_USERNAME = `
  SELECT ID, USERNAME, PASSWORD_HASH, NOMBRE, ROL, ACTIVO
  FROM ALLWAYS_ADMIN
  WHERE USERNAME = :username AND ACTIVO = 'S'
`;

const ADMIN_INSERT = `
  INSERT INTO ALLWAYS_ADMIN (
    USERNAME, PASSWORD_HASH, NOMBRE, ROL
  ) VALUES (
    :username, :passwordHash, :nombre, :rol
  )
`;

const ADMIN_COUNT = `
  SELECT COUNT(*) AS TOTAL FROM ALLWAYS_ADMIN
`;

const ADMIN_UPDATE_LOGIN = `
  UPDATE ALLWAYS_ADMIN SET ULTIMO_LOGIN = CURRENT_TIMESTAMP WHERE ID = :id
`;

// ============================================================
// ALLWAYS_ADMIN_LOG
// ============================================================

const ADMIN_LOG_INSERT = `
  INSERT INTO ALLWAYS_ADMIN_LOG (
    ADMIN_ID, ACCION, DETALLE, IP
  ) VALUES (
    :adminId, :accion, :detalle, :ip
  )
`;

// ============================================================
// DASHBOARD
// ============================================================

const DASHBOARD_STATS_TOTALS = `
  SELECT
    (SELECT COUNT(*) FROM ALLWAYS_PARTICIPANTES) AS TOTAL_PARTICIPANTES,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS) AS TOTAL_REGISTROS,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'PENDIENTE') AS PENDIENTES,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'ACEPTADO') AS ACEPTADOS,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'RECHAZADO') AS RECHAZADOS,
    (SELECT COUNT(*) FROM ALLWAYS_CUPONES) AS TOTAL_CUPONES
  FROM DUAL
`;

const DASHBOARD_STATS_TODAY = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE TRUNC(FECHA_REGISTRO) = TRUNC(SYSDATE)
`;

const DASHBOARD_STATS_WEEK = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= TRUNC(SYSDATE, 'IW')
`;

const DASHBOARD_STATS_MONTH = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= TRUNC(SYSDATE, 'MM')
`;

const DASHBOARD_CHART_DAILY = `
  SELECT TO_CHAR(FECHA_REGISTRO, 'YYYY-MM-DD') AS FECHA,
         COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= SYSDATE - 30
  GROUP BY TO_CHAR(FECHA_REGISTRO, 'YYYY-MM-DD')
  ORDER BY FECHA ASC
`;

const DASHBOARD_CHART_MONTHLY = `
  SELECT TO_CHAR(FECHA_REGISTRO, 'YYYY-MM') AS MES,
         COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  GROUP BY TO_CHAR(FECHA_REGISTRO, 'YYYY-MM')
  ORDER BY MES ASC
`;

const DASHBOARD_TOP_CLIENTES = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.DEPARTAMENTO,
         COUNT(C.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_PARTICIPANTES P
  JOIN ALLWAYS_CUPONES C ON C.PARTICIPANTE_ID = P.ID
  GROUP BY P.ID, P.NOMBRE, P.CEDULA, P.DEPARTAMENTO
  ORDER BY TOTAL_CUPONES DESC
  FETCH FIRST 10 ROWS ONLY
`;

const DASHBOARD_MAPA = `
  SELECT P.DEPARTAMENTO, COUNT(DISTINCT P.ID) AS TOTAL_PARTICIPANTES,
         COUNT(DISTINCT R.ID) AS TOTAL_REGISTROS
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_REGISTROS R ON R.PARTICIPANTE_ID = P.ID
  WHERE P.DEPARTAMENTO IS NOT NULL
  GROUP BY P.DEPARTAMENTO
  ORDER BY TOTAL_PARTICIPANTES DESC
`;

module.exports = {
  PARTICIPANTE_INSERT,
  PARTICIPANTE_FIND_BY_CEDULA,
  PARTICIPANTE_FIND_BY_ID,
  PARTICIPANTE_LIST,
  PARTICIPANTE_LIST_COUNT,
  PARTICIPANTE_DETAIL,
  PARTICIPANTE_REGISTROS,
  REGISTRO_INSERT,
  REGISTRO_FIND_BY_ID,
  REGISTRO_LIST,
  REGISTRO_LIST_COUNT,
  REGISTRO_UPDATE_ESTADO,
  CUPON_INSERT,
  CUPON_FIND_BY_CODIGO,
  CUPON_LIST_BY_CEDULA,
  CUPON_LIST_BY_REGISTRO,
  CUPON_LIST_ALL,
  CUPON_LIST_ALL_COUNT,
  PREMIO_LIST,
  ADMIN_FIND_BY_USERNAME,
  ADMIN_INSERT,
  ADMIN_COUNT,
  ADMIN_UPDATE_LOGIN,
  ADMIN_LOG_INSERT,
  DASHBOARD_STATS_TOTALS,
  DASHBOARD_STATS_TODAY,
  DASHBOARD_STATS_WEEK,
  DASHBOARD_STATS_MONTH,
  DASHBOARD_CHART_DAILY,
  DASHBOARD_CHART_MONTHLY,
  DASHBOARD_TOP_CLIENTES,
  DASHBOARD_MAPA
};
