'use strict';

/**
 * Centralized SQL queries for the Allways Show de Premios application.
 * All table names use ALLWAYS_ prefix matching Oracle 19C schema.
 * All queries use bind parameters to prevent SQL injection.
 */

// ============================================================
// ALLWAYS_PARTICIPANTES
// ============================================================

const PARTICIPANTE_INSERT = `
  INSERT INTO ALLWAYS_PARTICIPANTES (
    NOMBRE, CEDULA, TELEFONO, EMAIL, CIUDAD, DEPARTAMENTO,
    DEPARTAMENTO_ID, DISTRITO_ID, CIUDAD_ID, BARRIO_ID,
    CALLE, NUMERO_CASA, COMPLEMENTO
  ) VALUES (
    :nombre, :cedula, :telefono, :email, :ciudad, :departamento,
    :departamentoId, :distritoId, :ciudadId, :barrioId,
    :calle, :numeroCasa, :complemento
  ) RETURNING ID INTO :id
`;

const PARTICIPANTE_FIND_BY_CEDULA = `
  SELECT ID, NOMBRE, CEDULA, TELEFONO, EMAIL,
         CIUDAD, DEPARTAMENTO,
         DEPARTAMENTO_ID, DISTRITO_ID, CIUDAD_ID, BARRIO_ID,
         FECHA_REGISTRO, ACTIVO
  FROM ALLWAYS_PARTICIPANTES
  WHERE CEDULA = :cedula
`;

const PARTICIPANTE_FIND_BY_ID = `
  SELECT ID, NOMBRE, CEDULA, TELEFONO, EMAIL,
         CIUDAD, DEPARTAMENTO,
         DEPARTAMENTO_ID, DISTRITO_ID, CIUDAD_ID, BARRIO_ID,
         FECHA_REGISTRO, ACTIVO
  FROM ALLWAYS_PARTICIPANTES
  WHERE ID = :id
`;

const PARTICIPANTE_LIST = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         P.CALLE, P.NUMERO_CASA, P.COMPLEMENTO,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO,
         P.FECHA_REGISTRO,
         COUNT(DISTINCT R.ID) AS TOTAL_REGISTROS,
         COUNT(DISTINCT C.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_REGISTROS R ON R.PARTICIPANTE_ID = P.ID
  LEFT JOIN ALLWAYS_CUPONES C ON C.PARTICIPANTE_ID = P.ID
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE 1=1
`;

const PARTICIPANTE_LIST_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_PARTICIPANTES
  WHERE 1=1
`;

const PARTICIPANTE_DETAIL = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         P.DEPARTAMENTO_ID, P.DISTRITO_ID, P.CIUDAD_ID, P.BARRIO_ID,
         P.CALLE, P.NUMERO_CASA, P.COMPLEMENTO,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO,
         P.FECHA_REGISTRO, P.ACTIVO
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE P.ID = :id
`;

const PARTICIPANTE_REGISTROS = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.IMAGEN_FACTURA, R.IMAGEN_PRODUCTOS,
         R.MOTIVO_RECHAZO, R.FECHA_VALIDACION,
         R.TIENDA, R.VENDEDOR
  FROM ALLWAYS_REGISTROS R
  WHERE R.PARTICIPANTE_ID = :participanteId
  ORDER BY R.FECHA_REGISTRO DESC
`;

// ============================================================
// ALLWAYS_REGISTROS
// ============================================================

const REGISTRO_INSERT = `
  INSERT INTO ALLWAYS_REGISTROS (
    PARTICIPANTE_ID, NUMERO_FACTURA, CANTIDAD_PRODUCTOS,
    IMAGEN_FACTURA, IMAGEN_PRODUCTOS, ESTADO, IP_REGISTRO,
    TIENDA, VENDEDOR
  ) VALUES (
    :participanteId, :numeroFactura, :cantidadProductos,
    :imagenFactura, :imagenProductos, 'PENDIENTE', :ipRegistro,
    :tienda, :vendedor
  ) RETURNING ID INTO :id
`;

const REGISTRO_FIND_BY_ID = `
  SELECT R.ID, R.PARTICIPANTE_ID, R.NUMERO_FACTURA,
         R.CANTIDAD_PRODUCTOS, R.IMAGEN_FACTURA, R.IMAGEN_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         R.VALIDADO_POR, R.MOTIVO_RECHAZO, R.IP_REGISTRO,
         R.TIENDA, R.VENDEDOR,
         P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         P.DEPARTAMENTO_ID, P.DISTRITO_ID, P.CIUDAD_ID, P.BARRIO_ID,
         P.CALLE, P.NUMERO_CASA, P.COMPLEMENTO,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE R.ID = :id
`;

const REGISTRO_LIST = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         R.TIENDA, R.VENDEDOR,
         P.NOMBRE, P.CEDULA, P.TELEFONO
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  WHERE 1=1
`;

const REGISTRO_LIST_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  WHERE 1=1
`;

const REGISTRO_UPDATE_ESTADO = `
  UPDATE ALLWAYS_REGISTROS SET
    ESTADO = :estado,
    FECHA_VALIDACION = CURRENT_TIMESTAMP,
    VALIDADO_POR = :validadoPor,
    MOTIVO_RECHAZO = :motivoRechazo
  WHERE ID = :id
`;

const REGISTRO_UPDATE_FIELDS = `
  UPDATE ALLWAYS_REGISTROS SET
    NUMERO_FACTURA = :numeroFactura,
    CANTIDAD_PRODUCTOS = :cantidadProductos,
    TIENDA = :tienda,
    VENDEDOR = :vendedor
  WHERE ID = :id AND ESTADO = 'PENDIENTE'
`;

// ============================================================
// ALLWAYS_CUPONES
// ============================================================

const CUPON_INSERT = `
  INSERT INTO ALLWAYS_CUPONES (
    REGISTRO_ID, PARTICIPANTE_ID, NUMERO_CUPON, MES_SORTEO
  ) VALUES (
    :registroId, :participanteId, :numeroCupon, :mesSorteo
  )
`;

const CUPON_FIND_BY_CODIGO = `
  SELECT ID, NUMERO_CUPON, REGISTRO_ID, PARTICIPANTE_ID, MES_SORTEO, FECHA_GENERACION
  FROM ALLWAYS_CUPONES
  WHERE NUMERO_CUPON = :numeroCupon
`;

const CUPON_LIST_BY_CEDULA = `
  SELECT C.ID, C.NUMERO_CUPON, C.MES_SORTEO, C.FECHA_GENERACION, C.GANADOR,
         R.NUMERO_FACTURA, R.ESTADO AS ESTADO_REGISTRO
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  WHERE P.CEDULA = :cedula
  ORDER BY C.FECHA_GENERACION DESC
`;

const CUPON_LIST_BY_REGISTRO = `
  SELECT ID, NUMERO_CUPON, MES_SORTEO, FECHA_GENERACION, GANADOR
  FROM ALLWAYS_CUPONES
  WHERE REGISTRO_ID = :registroId
  ORDER BY FECHA_GENERACION DESC
`;

const CUPON_LIST_ALL = `
  SELECT C.ID, C.NUMERO_CUPON, C.MES_SORTEO, C.FECHA_GENERACION, C.GANADOR,
         P.NOMBRE, P.CEDULA,
         R.NUMERO_FACTURA
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  WHERE 1=1
`;

const CUPON_LIST_ALL_COUNT = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  WHERE 1=1
`;

// ============================================================
// ALLWAYS_PREMIOS
// ============================================================

const PREMIO_LIST = `
  SELECT ID, MES, DESCRIPCION, IMAGEN, CUPON_GANADOR_ID, FECHA_SORTEO, ACTIVO
  FROM ALLWAYS_PREMIOS
  WHERE ACTIVO = 'S'
  ORDER BY ID ASC
`;

// ============================================================
// ALLWAYS_ADMIN
// ============================================================

const ADMIN_FIND_BY_USERNAME = `
  SELECT ID, USERNAME, PASSWORD_HASH, NOMBRE, ROL, ACTIVO
  FROM ALLWAYS_ADMIN
  WHERE USERNAME = :username AND ACTIVO = 'S'
`;

const ADMIN_INSERT = `
  INSERT INTO ALLWAYS_ADMIN (
    USERNAME, PASSWORD_HASH, NOMBRE, ROL
  ) VALUES (
    :username, :passwordHash, :nombre, :rol
  )
`;

const ADMIN_COUNT = `
  SELECT COUNT(*) AS TOTAL FROM ALLWAYS_ADMIN
`;

const ADMIN_UPDATE_LOGIN = `
  UPDATE ALLWAYS_ADMIN SET ULTIMO_LOGIN = CURRENT_TIMESTAMP WHERE ID = :id
`;

const ADMIN_UPDATE_PASSWORD = `
  UPDATE ALLWAYS_ADMIN SET PASSWORD_HASH = :passwordHash WHERE ID = :id
`;

const ADMIN_FIND_BY_ID = `
  SELECT ID, USERNAME, PASSWORD_HASH, NOMBRE, ROL, ACTIVO
  FROM ALLWAYS_ADMIN
  WHERE ID = :id AND ACTIVO = 'S'
`;

// ============================================================
// ALLWAYS_ADMIN_LOG
// ============================================================

const ADMIN_LOG_INSERT = `
  INSERT INTO ALLWAYS_ADMIN_LOG (
    ADMIN_ID, ACCION, DETALLE, IP
  ) VALUES (
    :adminId, :accion, :detalle, :ip
  )
`;

// ============================================================
// DASHBOARD
// ============================================================

const DASHBOARD_STATS_TOTALS = `
  SELECT
    (SELECT COUNT(*) FROM ALLWAYS_PARTICIPANTES) AS TOTAL_PARTICIPANTES,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS) AS TOTAL_REGISTROS,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'PENDIENTE') AS PENDIENTES,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'ACEPTADO') AS ACEPTADOS,
    (SELECT COUNT(*) FROM ALLWAYS_REGISTROS WHERE ESTADO = 'RECHAZADO') AS RECHAZADOS,
    (SELECT COUNT(*) FROM ALLWAYS_CUPONES) AS TOTAL_CUPONES
  FROM DUAL
`;

const DASHBOARD_STATS_TODAY = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE TRUNC(FECHA_REGISTRO) = TRUNC(SYSDATE)
`;

const DASHBOARD_STATS_WEEK = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= TRUNC(SYSDATE, 'IW')
`;

const DASHBOARD_STATS_MONTH = `
  SELECT COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= TRUNC(SYSDATE, 'MM')
`;

const DASHBOARD_CHART_DAILY = `
  SELECT TO_CHAR(FECHA_REGISTRO, 'YYYY-MM-DD') AS FECHA,
         COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  WHERE FECHA_REGISTRO >= SYSDATE - 30
  GROUP BY TO_CHAR(FECHA_REGISTRO, 'YYYY-MM-DD')
  ORDER BY FECHA ASC
`;

const DASHBOARD_CHART_MONTHLY = `
  SELECT TO_CHAR(FECHA_REGISTRO, 'YYYY-MM') AS MES,
         COUNT(*) AS TOTAL
  FROM ALLWAYS_REGISTROS
  GROUP BY TO_CHAR(FECHA_REGISTRO, 'YYYY-MM')
  ORDER BY MES ASC
`;

const DASHBOARD_TOP_CLIENTES = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.DEPARTAMENTO,
         COUNT(C.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_PARTICIPANTES P
  JOIN ALLWAYS_CUPONES C ON C.PARTICIPANTE_ID = P.ID
  GROUP BY P.ID, P.NOMBRE, P.CEDULA, P.DEPARTAMENTO
  ORDER BY TOTAL_CUPONES DESC
  FETCH FIRST 10 ROWS ONLY
`;

const DASHBOARD_MAPA = `
  SELECT P.DEPARTAMENTO, COUNT(DISTINCT P.ID) AS TOTAL_PARTICIPANTES,
         COUNT(DISTINCT R.ID) AS TOTAL_REGISTROS
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_REGISTROS R ON R.PARTICIPANTE_ID = P.ID
  WHERE P.DEPARTAMENTO IS NOT NULL
  GROUP BY P.DEPARTAMENTO
  ORDER BY TOTAL_PARTICIPANTES DESC
`;

// ============================================================
// SORTEO (Draw system)
// ============================================================

const SORTEO_RESUMEN_MESES = `
  SELECT P.MES,
         COUNT(P.ID) AS TOTAL_PREMIOS,
         COUNT(P.CUPON_GANADOR_ID) AS PREMIOS_SORTEADOS,
         MIN(P.FECHA_SORTEO) AS FECHA_SORTEO,
         (SELECT COUNT(*) FROM ALLWAYS_CUPONES C2
          JOIN ALLWAYS_REGISTROS R2 ON R2.ID = C2.REGISTRO_ID
          WHERE R2.ESTADO = 'ACEPTADO' AND C2.GANADOR = 'N'
          AND DECODE(UPPER(C2.MES_SORTEO),
              'ENERO',1,'FEBRERO',2,'MARZO',3,'ABRIL',4,'MAYO',5,'JUNIO',6,
              'JULIO',7,'AGOSTO',8,'SEPTIEMBRE',9,'OCTUBRE',10,'NOVIEMBRE',11,'DICIEMBRE',12,99)
              <=
              DECODE(UPPER(P.MES),
              'ENERO',1,'FEBRERO',2,'MARZO',3,'ABRIL',4,'MAYO',5,'JUNIO',6,
              'JULIO',7,'AGOSTO',8,'SEPTIEMBRE',9,'OCTUBRE',10,'NOVIEMBRE',11,'DICIEMBRE',12,99)
         ) AS CUPONES_ELEGIBLES,
         (SELECT COUNT(*) FROM ALLWAYS_CUPONES C3
          WHERE UPPER(C3.MES_SORTEO) = UPPER(P.MES)
         ) AS TOTAL_CUPONES
  FROM ALLWAYS_PREMIOS P
  WHERE P.ACTIVO = 'S'
  GROUP BY P.MES
  ORDER BY DECODE(UPPER(P.MES),
    'ENERO',1,'FEBRERO',2,'MARZO',3,'ABRIL',4,'MAYO',5,'JUNIO',6,
    'JULIO',7,'AGOSTO',8,'SEPTIEMBRE',9,'OCTUBRE',10,'NOVIEMBRE',11,'DICIEMBRE',12,13)
`;

const SORTEO_PREMIOS_BY_MES = `
  SELECT P.ID, P.MES, P.DESCRIPCION, P.IMAGEN, P.CUPON_GANADOR_ID, P.FECHA_SORTEO,
         C.NUMERO_CUPON,
         PA.NOMBRE AS GANADOR_NOMBRE,
         PA.CEDULA AS GANADOR_CEDULA,
         PA.TELEFONO AS GANADOR_TELEFONO
  FROM ALLWAYS_PREMIOS P
  LEFT JOIN ALLWAYS_CUPONES C ON C.ID = P.CUPON_GANADOR_ID
  LEFT JOIN ALLWAYS_PARTICIPANTES PA ON PA.ID = C.PARTICIPANTE_ID
  WHERE P.ACTIVO = 'S' AND UPPER(P.MES) = UPPER(:mes)
  ORDER BY P.ID ASC
`;

// Cumulative eligibility: a coupon issued in any month <= :mes that hasn't won yet competes.
// This way a non-winning May coupon stays in the pot for June, July, ..., until it wins.
const SORTEO_CUPONES_ELEGIBLES = `
  SELECT C.ID, C.NUMERO_CUPON, C.PARTICIPANTE_ID,
         P.NOMBRE, P.CEDULA
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  WHERE R.ESTADO = 'ACEPTADO'
    AND C.GANADOR = 'N'
    AND DECODE(UPPER(C.MES_SORTEO),
        'ENERO',1,'FEBRERO',2,'MARZO',3,'ABRIL',4,'MAYO',5,'JUNIO',6,
        'JULIO',7,'AGOSTO',8,'SEPTIEMBRE',9,'OCTUBRE',10,'NOVIEMBRE',11,'DICIEMBRE',12,99)
        <=
        DECODE(UPPER(:mes),
        'ENERO',1,'FEBRERO',2,'MARZO',3,'ABRIL',4,'MAYO',5,'JUNIO',6,
        'JULIO',7,'AGOSTO',8,'SEPTIEMBRE',9,'OCTUBRE',10,'NOVIEMBRE',11,'DICIEMBRE',12,99)
  ORDER BY DBMS_RANDOM.VALUE
`;

const SORTEO_MARCAR_GANADOR_CUPON = `
  UPDATE ALLWAYS_CUPONES SET GANADOR = 'S' WHERE ID = :cuponId
`;

const SORTEO_MARCAR_GANADOR_PREMIO = `
  UPDATE ALLWAYS_PREMIOS
  SET CUPON_GANADOR_ID = :cuponId, FECHA_SORTEO = CURRENT_TIMESTAMP
  WHERE ID = :premioId
`;

const SORTEO_RESET_CUPONES = `
  UPDATE ALLWAYS_CUPONES SET GANADOR = 'N'
  WHERE ID IN (
    SELECT P.CUPON_GANADOR_ID FROM ALLWAYS_PREMIOS P
    WHERE UPPER(P.MES) = UPPER(:mes) AND P.CUPON_GANADOR_ID IS NOT NULL
  )
`;

const SORTEO_RESET_PREMIOS = `
  UPDATE ALLWAYS_PREMIOS
  SET CUPON_GANADOR_ID = NULL, FECHA_SORTEO = NULL
  WHERE UPPER(MES) = UPPER(:mes) AND ACTIVO = 'S'
`;

// ============================================================
// ALLWAYS_GEO (Geographic reference)
// ============================================================

const GEO_DEPARTAMENTOS = `
  SELECT ID, NOMBRE FROM ALLWAYS_GEO_DEPARTAMENTOS ORDER BY NOMBRE ASC
`;

const GEO_DISTRITOS = `
  SELECT ID, NOMBRE FROM ALLWAYS_GEO_DISTRITOS
  WHERE DEPARTAMENTO_ID = :departamentoId
  ORDER BY NOMBRE ASC
`;

const GEO_CIUDADES = `
  SELECT ID, NOMBRE FROM ALLWAYS_GEO_CIUDADES
  WHERE DEPARTAMENTO_ID = :departamentoId AND DISTRITO_ID = :distritoId
  ORDER BY NOMBRE ASC
`;

const GEO_BARRIOS = `
  SELECT ID, NOMBRE FROM ALLWAYS_GEO_BARRIOS
  WHERE DEPARTAMENTO_ID = :departamentoId AND DISTRITO_ID = :distritoId AND CIUDAD_ID = :ciudadId
  ORDER BY NOMBRE ASC
`;

// ============================================================
// ALLWAYS_WA_*  (WhatsApp module)
// ============================================================

const WA_INSTANCIA_GET = `
  SELECT ID, NOMBRE, NUMERO, ESTADO, QR_CODE, ULTIMA_CONEXION, ULTIMO_EVENTO, FECHA_CREACION
  FROM ALLWAYS_WA_INSTANCIA
  WHERE NOMBRE = :nombre
`;

const WA_INSTANCIA_UPSERT = `
  MERGE INTO ALLWAYS_WA_INSTANCIA t
  USING (SELECT :nombre AS NOMBRE FROM DUAL) s ON (t.NOMBRE = s.NOMBRE)
  WHEN MATCHED THEN UPDATE SET t.ESTADO = :estado, t.ULTIMO_EVENTO = :evento, t.NUMERO = NVL(:numero, t.NUMERO),
                               t.ULTIMA_CONEXION = CASE WHEN :estado = 'CONECTADA' THEN CURRENT_TIMESTAMP ELSE t.ULTIMA_CONEXION END,
                               t.QR_CODE = CASE WHEN :estado = 'CONECTADA' THEN NULL ELSE t.QR_CODE END
  WHEN NOT MATCHED THEN INSERT (NOMBRE, NUMERO, ESTADO, ULTIMO_EVENTO) VALUES (:nombre, :numero, :estado, :evento)
`;

const WA_INSTANCIA_SET_QR = `
  MERGE INTO ALLWAYS_WA_INSTANCIA t
  USING (SELECT :nombre AS NOMBRE FROM DUAL) s ON (t.NOMBRE = s.NOMBRE)
  WHEN MATCHED THEN UPDATE SET t.QR_CODE = :qrCode, t.ESTADO = 'QR_PENDIENTE', t.ULTIMO_EVENTO = 'qrcode.updated'
  WHEN NOT MATCHED THEN INSERT (NOMBRE, ESTADO, QR_CODE, ULTIMO_EVENTO)
                       VALUES (:nombre, 'QR_PENDIENTE', :qrCode, 'qrcode.updated')
`;

const WA_PLANTILLA_GET = `
  SELECT ID, CODIGO, NOMBRE, TEXTO, ACTIVO
  FROM ALLWAYS_WA_PLANTILLAS
  WHERE CODIGO = :codigo AND ACTIVO = 'S'
`;

const WA_PLANTILLA_LIST = `
  SELECT ID, CODIGO, NOMBRE, TEXTO, ACTIVO, FECHA_MODIFICACION
  FROM ALLWAYS_WA_PLANTILLAS
  ORDER BY CODIGO ASC
`;

const WA_PLANTILLA_UPDATE = `
  UPDATE ALLWAYS_WA_PLANTILLAS
  SET TEXTO = :texto, NOMBRE = :nombre, ACTIVO = :activo, FECHA_MODIFICACION = CURRENT_TIMESTAMP
  WHERE CODIGO = :codigo
`;

const WA_CHAT_FIND_BY_JID = `
  SELECT ID, PARTICIPANTE_ID, TELEFONO, REMOTE_JID, NOMBRE_CONTACTO, ULTIMA_ACTIVIDAD, NO_LEIDOS
  FROM ALLWAYS_WA_CHATS
  WHERE REMOTE_JID = :remoteJid
`;

const WA_CHAT_INSERT = `
  INSERT INTO ALLWAYS_WA_CHATS (PARTICIPANTE_ID, TELEFONO, REMOTE_JID, NOMBRE_CONTACTO)
  VALUES (:participanteId, :telefono, :remoteJid, :nombreContacto)
  RETURNING ID INTO :id
`;

const WA_CHAT_UPDATE_ACTIVIDAD = `
  UPDATE ALLWAYS_WA_CHATS
  SET ULTIMA_ACTIVIDAD = CURRENT_TIMESTAMP,
      NO_LEIDOS = NO_LEIDOS + :incNoLeidos,
      NOMBRE_CONTACTO = NVL(:nombreContacto, NOMBRE_CONTACTO),
      PARTICIPANTE_ID = NVL(PARTICIPANTE_ID, :participanteId)
  WHERE ID = :id
`;

const WA_CHAT_MARK_READ = `
  UPDATE ALLWAYS_WA_CHATS SET NO_LEIDOS = 0 WHERE ID = :id
`;

const WA_CHAT_LIST = `
  SELECT C.ID, C.PARTICIPANTE_ID, C.TELEFONO, C.REMOTE_JID, C.NOMBRE_CONTACTO,
         C.ULTIMA_ACTIVIDAD, C.NO_LEIDOS,
         P.NOMBRE AS PARTICIPANTE_NOMBRE, P.CEDULA AS PARTICIPANTE_CEDULA,
         (SELECT TEXTO FROM (
            SELECT TEXTO FROM ALLWAYS_WA_MENSAJES M
             WHERE M.CHAT_ID = C.ID ORDER BY M.FECHA DESC
          ) WHERE ROWNUM = 1) AS ULTIMO_TEXTO
  FROM ALLWAYS_WA_CHATS C
  LEFT JOIN ALLWAYS_PARTICIPANTES P ON P.ID = C.PARTICIPANTE_ID
  ORDER BY C.ULTIMA_ACTIVIDAD DESC
  OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
`;

const WA_CHAT_LIST_COUNT = `
  SELECT COUNT(*) AS TOTAL FROM ALLWAYS_WA_CHATS
`;

const WA_MENSAJE_INSERT = `
  INSERT INTO ALLWAYS_WA_MENSAJES (
    CHAT_ID, DIRECCION, TEXTO, TIPO, EVOLUTION_MESSAGE_ID,
    ESTADO, PLANTILLA_CODIGO, REGISTRO_ID, ENVIADO_POR_ADMIN
  ) VALUES (
    :chatId, :direccion, :texto, :tipo, :evolutionMessageId,
    :estado, :plantillaCodigo, :registroId, :enviadoPorAdmin
  ) RETURNING ID INTO :id
`;

const WA_MENSAJE_LIST_BY_CHAT = `
  SELECT M.ID, M.CHAT_ID, M.DIRECCION, M.TEXTO, M.TIPO, M.EVOLUTION_MESSAGE_ID,
         M.ESTADO, M.PLANTILLA_CODIGO, M.REGISTRO_ID, M.ENVIADO_POR_ADMIN, M.FECHA,
         A.NOMBRE AS ADMIN_NOMBRE, A.USERNAME AS ADMIN_USERNAME
  FROM ALLWAYS_WA_MENSAJES M
  LEFT JOIN ALLWAYS_ADMIN A ON A.ID = M.ENVIADO_POR_ADMIN
  WHERE M.CHAT_ID = :chatId
  ORDER BY M.FECHA ASC
  OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
`;

const WA_NOTIF_LOG_INSERT = `
  INSERT INTO ALLWAYS_WA_LOG_NOTIF (REGISTRO_ID, PARTICIPANTE_ID, TIPO, EXITOSO, MENSAJE_ID, ERROR_DETALLE)
  VALUES (:registroId, :participanteId, :tipo, :exitoso, :mensajeId, :errorDetalle)
`;

// ============================================================
// Cliente Area (auth + tokens + audit)
// ============================================================

const CLIENTE_FIND_BY_CEDULA_AUTH = `
  SELECT ID, NOMBRE, CEDULA, TELEFONO, EMAIL,
         PASSWORD_HASH, INTENTOS_FALLIDOS, BLOQUEADO_HASTA, ULTIMO_LOGIN,
         ACTIVO
  FROM ALLWAYS_PARTICIPANTES
  WHERE CEDULA = :cedula
`;

const CLIENTE_DETAIL_FOR_ME = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         P.DEPARTAMENTO_ID, P.DISTRITO_ID, P.CIUDAD_ID, P.BARRIO_ID,
         P.CALLE, P.NUMERO_CASA, P.COMPLEMENTO,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO,
         P.FECHA_REGISTRO, P.PASSWORD_SET_AT, P.ULTIMO_LOGIN
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE P.ID = :id
`;

const CLIENTE_REGISTROS = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         R.MOTIVO_RECHAZO, R.IMAGEN_FACTURA, R.IMAGEN_PRODUCTOS,
         R.TIENDA, R.VENDEDOR,
         (SELECT COUNT(*) FROM ALLWAYS_CUPONES C WHERE C.REGISTRO_ID = R.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_REGISTROS R
  WHERE R.PARTICIPANTE_ID = :participanteId
  ORDER BY R.FECHA_REGISTRO DESC
`;

const CLIENTE_CUPONES = `
  SELECT C.ID, C.NUMERO_CUPON, C.MES_SORTEO, C.FECHA_GENERACION, C.GANADOR,
         R.NUMERO_FACTURA, R.TIENDA, R.FECHA_REGISTRO AS FECHA_REGISTRO_FACTURA
  FROM ALLWAYS_CUPONES C
  JOIN ALLWAYS_REGISTROS R ON R.ID = C.REGISTRO_ID
  WHERE C.PARTICIPANTE_ID = :participanteId
  ORDER BY C.FECHA_GENERACION DESC
`;

const CLIENTE_UPDATE_LOGIN_OK = `
  UPDATE ALLWAYS_PARTICIPANTES
  SET ULTIMO_LOGIN = CURRENT_TIMESTAMP,
      INTENTOS_FALLIDOS = 0,
      BLOQUEADO_HASTA = NULL
  WHERE ID = :id
`;

const CLIENTE_UPDATE_LOGIN_FAIL = `
  UPDATE ALLWAYS_PARTICIPANTES
  SET INTENTOS_FALLIDOS = NVL(INTENTOS_FALLIDOS, 0) + 1,
      BLOQUEADO_HASTA = CASE
        WHEN NVL(INTENTOS_FALLIDOS, 0) + 1 >= 5
          THEN CURRENT_TIMESTAMP + NUMTODSINTERVAL(15, 'MINUTE')
        ELSE BLOQUEADO_HASTA
      END
  WHERE ID = :id
`;

const CLIENTE_SET_PASSWORD = `
  UPDATE ALLWAYS_PARTICIPANTES
  SET PASSWORD_HASH = :passwordHash,
      PASSWORD_SET_AT = CURRENT_TIMESTAMP,
      INTENTOS_FALLIDOS = 0,
      BLOQUEADO_HASTA = NULL,
      EMAIL = NVL(:email, EMAIL)
  WHERE ID = :id
`;

const CLIENTE_UPDATE_EMAIL = `
  UPDATE ALLWAYS_PARTICIPANTES SET EMAIL = :email WHERE ID = :id
`;

const TOKEN_INSERT = `
  INSERT INTO ALLWAYS_PARTICIPANTE_TOKEN (
    PARTICIPANTE_ID, TIPO, TOKEN_HASH, EXPIRA_EN, IP_SOLICITUD
  ) VALUES (
    :participanteId, :tipo, :tokenHash,
    CURRENT_TIMESTAMP + NUMTODSINTERVAL(:expiraMinutos, 'MINUTE'),
    :ipSolicitud
  ) RETURNING ID INTO :id
`;

const TOKEN_FIND_BY_HASH = `
  SELECT ID, PARTICIPANTE_ID, TIPO, EXPIRA_EN, USADO_EN
  FROM ALLWAYS_PARTICIPANTE_TOKEN
  WHERE TOKEN_HASH = :tokenHash
`;

const TOKEN_MARK_USED = `
  UPDATE ALLWAYS_PARTICIPANTE_TOKEN
  SET USADO_EN = CURRENT_TIMESTAMP
  WHERE ID = :id
`;

const TOKEN_INVALIDATE_ALL_FOR = `
  UPDATE ALLWAYS_PARTICIPANTE_TOKEN
  SET USADO_EN = CURRENT_TIMESTAMP
  WHERE PARTICIPANTE_ID = :participanteId
    AND TIPO = :tipo
    AND USADO_EN IS NULL
`;

const CLIENTE_LOG_INSERT = `
  INSERT INTO ALLWAYS_CLIENTE_LOG (
    PARTICIPANTE_ID, CEDULA, EVENTO, EXITOSO, DETALLE, IP, USER_AGENT
  ) VALUES (
    :participanteId, :cedula, :evento, :exitoso, :detalle, :ip, :userAgent
  )
`;

// ============================================================
// EXPORT QUERIES (sin paginacion, todas las columnas relevantes)
// ============================================================

const PARTICIPANTE_EXPORT = `
  SELECT P.ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         P.CALLE, P.NUMERO_CASA, P.COMPLEMENTO,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO,
         P.FECHA_REGISTRO, P.ACTIVO,
         COUNT(DISTINCT R.ID) AS TOTAL_REGISTROS,
         SUM(CASE WHEN R.ESTADO = 'ACEPTADO'  THEN 1 ELSE 0 END) AS REG_ACEPTADOS,
         SUM(CASE WHEN R.ESTADO = 'RECHAZADO' THEN 1 ELSE 0 END) AS REG_RECHAZADOS,
         SUM(CASE WHEN R.ESTADO = 'PENDIENTE' THEN 1 ELSE 0 END) AS REG_PENDIENTES,
         COUNT(DISTINCT C.ID) AS TOTAL_CUPONES
  FROM ALLWAYS_PARTICIPANTES P
  LEFT JOIN ALLWAYS_REGISTROS R ON R.PARTICIPANTE_ID = P.ID
  LEFT JOIN ALLWAYS_CUPONES C ON C.PARTICIPANTE_ID = P.ID
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE 1=1
`;

const REGISTRO_EXPORT = `
  SELECT R.ID, R.NUMERO_FACTURA, R.CANTIDAD_PRODUCTOS,
         R.ESTADO, R.FECHA_REGISTRO, R.FECHA_VALIDACION,
         R.MOTIVO_RECHAZO, R.TIENDA, R.VENDEDOR, R.IP_REGISTRO,
         P.ID AS PARTICIPANTE_ID, P.NOMBRE, P.CEDULA, P.TELEFONO, P.EMAIL,
         P.DEPARTAMENTO, P.CIUDAD,
         GD.NOMBRE AS GEO_DEPARTAMENTO,
         GDI.NOMBRE AS GEO_DISTRITO,
         GC.NOMBRE AS GEO_CIUDAD,
         GB.NOMBRE AS GEO_BARRIO,
         (SELECT COUNT(*) FROM ALLWAYS_CUPONES C WHERE C.REGISTRO_ID = R.ID) AS CUPONES_GENERADOS
  FROM ALLWAYS_REGISTROS R
  JOIN ALLWAYS_PARTICIPANTES P ON P.ID = R.PARTICIPANTE_ID
  LEFT JOIN ALLWAYS_GEO_DEPARTAMENTOS GD ON GD.ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_DISTRITOS GDI ON GDI.ID = P.DISTRITO_ID AND GDI.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID
  LEFT JOIN ALLWAYS_GEO_CIUDADES GC ON GC.ID = P.CIUDAD_ID AND GC.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GC.DISTRITO_ID = P.DISTRITO_ID
  LEFT JOIN ALLWAYS_GEO_BARRIOS GB ON GB.ID = P.BARRIO_ID AND GB.DEPARTAMENTO_ID = P.DEPARTAMENTO_ID AND GB.DISTRITO_ID = P.DISTRITO_ID AND GB.CIUDAD_ID = P.CIUDAD_ID
  WHERE 1=1
`;

module.exports = {
  PARTICIPANTE_INSERT,
  PARTICIPANTE_FIND_BY_CEDULA,
  PARTICIPANTE_FIND_BY_ID,
  PARTICIPANTE_LIST,
  PARTICIPANTE_LIST_COUNT,
  PARTICIPANTE_DETAIL,
  PARTICIPANTE_REGISTROS,
  PARTICIPANTE_EXPORT,
  REGISTRO_INSERT,
  REGISTRO_FIND_BY_ID,
  REGISTRO_LIST,
  REGISTRO_LIST_COUNT,
  REGISTRO_EXPORT,
  REGISTRO_UPDATE_ESTADO,
  REGISTRO_UPDATE_FIELDS,
  CUPON_INSERT,
  CUPON_FIND_BY_CODIGO,
  CUPON_LIST_BY_CEDULA,
  CUPON_LIST_BY_REGISTRO,
  CUPON_LIST_ALL,
  CUPON_LIST_ALL_COUNT,
  PREMIO_LIST,
  ADMIN_FIND_BY_USERNAME,
  ADMIN_INSERT,
  ADMIN_COUNT,
  ADMIN_UPDATE_LOGIN,
  ADMIN_UPDATE_PASSWORD,
  ADMIN_FIND_BY_ID,
  ADMIN_LOG_INSERT,
  DASHBOARD_STATS_TOTALS,
  DASHBOARD_STATS_TODAY,
  DASHBOARD_STATS_WEEK,
  DASHBOARD_STATS_MONTH,
  DASHBOARD_CHART_DAILY,
  DASHBOARD_CHART_MONTHLY,
  DASHBOARD_TOP_CLIENTES,
  DASHBOARD_MAPA,
  SORTEO_RESUMEN_MESES,
  SORTEO_PREMIOS_BY_MES,
  SORTEO_CUPONES_ELEGIBLES,
  SORTEO_MARCAR_GANADOR_CUPON,
  SORTEO_MARCAR_GANADOR_PREMIO,
  SORTEO_RESET_CUPONES,
  SORTEO_RESET_PREMIOS,
  GEO_DEPARTAMENTOS,
  GEO_DISTRITOS,
  GEO_CIUDADES,
  GEO_BARRIOS,
  WA_INSTANCIA_GET,
  WA_INSTANCIA_UPSERT,
  WA_INSTANCIA_SET_QR,
  WA_PLANTILLA_GET,
  WA_PLANTILLA_LIST,
  WA_PLANTILLA_UPDATE,
  WA_CHAT_FIND_BY_JID,
  WA_CHAT_INSERT,
  WA_CHAT_UPDATE_ACTIVIDAD,
  WA_CHAT_MARK_READ,
  WA_CHAT_LIST,
  WA_CHAT_LIST_COUNT,
  WA_MENSAJE_INSERT,
  WA_MENSAJE_LIST_BY_CHAT,
  WA_NOTIF_LOG_INSERT,
  CLIENTE_FIND_BY_CEDULA_AUTH,
  CLIENTE_DETAIL_FOR_ME,
  CLIENTE_REGISTROS,
  CLIENTE_CUPONES,
  CLIENTE_UPDATE_LOGIN_OK,
  CLIENTE_UPDATE_LOGIN_FAIL,
  CLIENTE_SET_PASSWORD,
  CLIENTE_UPDATE_EMAIL,
  TOKEN_INSERT,
  TOKEN_FIND_BY_HASH,
  TOKEN_MARK_USED,
  TOKEN_INVALIDATE_ALL_FOR,
  CLIENTE_LOG_INSERT
};
