-- ============================================================
-- Allways Show de Premios - Table Creation Script
-- Oracle 19C
-- ============================================================
-- Order: ALLWAYS_ADMIN first (referenced by ALLWAYS_REGISTROS FK),
--        then ALLWAYS_PARTICIPANTES, ALLWAYS_REGISTROS,
--        ALLWAYS_CUPONES, ALLWAYS_PREMIOS, ALLWAYS_ADMIN_LOG.
-- ============================================================

-- 1. ALLWAYS_ADMIN (must exist before ALLWAYS_REGISTROS)
CREATE TABLE ALLWAYS_ADMIN (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    NOMBRE VARCHAR2(200),
    ROL VARCHAR2(20) DEFAULT 'ADMIN',
    ACTIVO CHAR(1) DEFAULT 'S',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_LOGIN TIMESTAMP
);

-- 2. ALLWAYS_PARTICIPANTES
CREATE TABLE ALLWAYS_PARTICIPANTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    CEDULA VARCHAR2(20) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(200),
    CIUDAD VARCHAR2(100),
    DEPARTAMENTO VARCHAR2(100),
    LATITUD NUMBER(10,7),
    LONGITUD NUMBER(10,7),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT UK_CEDULA UNIQUE (CEDULA)
);

-- 3. ALLWAYS_REGISTROS (FK to ALLWAYS_PARTICIPANTES and ALLWAYS_ADMIN)
CREATE TABLE ALLWAYS_REGISTROS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PARTICIPANTE_ID NUMBER NOT NULL,
    NUMERO_FACTURA VARCHAR2(50) NOT NULL,
    CANTIDAD_PRODUCTOS NUMBER NOT NULL,
    IMAGEN_FACTURA VARCHAR2(500) NOT NULL,
    IMAGEN_PRODUCTOS VARCHAR2(500),
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE',
    MOTIVO_RECHAZO VARCHAR2(500),
    VALIDADO_POR NUMBER,
    FECHA_VALIDACION TIMESTAMP,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_REGISTRO VARCHAR2(45),
    CONSTRAINT FK_REG_PART FOREIGN KEY (PARTICIPANTE_ID) REFERENCES ALLWAYS_PARTICIPANTES(ID),
    CONSTRAINT FK_REG_ADMIN FOREIGN KEY (VALIDADO_POR) REFERENCES ALLWAYS_ADMIN(ID),
    CONSTRAINT CK_ESTADO CHECK (ESTADO IN ('PENDIENTE','ACEPTADO','RECHAZADO'))
);

-- 4. ALLWAYS_CUPONES
CREATE TABLE ALLWAYS_CUPONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGISTRO_ID NUMBER NOT NULL,
    PARTICIPANTE_ID NUMBER NOT NULL,
    NUMERO_CUPON VARCHAR2(20) NOT NULL UNIQUE,
    MES_SORTEO VARCHAR2(20),
    GANADOR CHAR(1) DEFAULT 'N',
    FECHA_GENERACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CUP_REG FOREIGN KEY (REGISTRO_ID) REFERENCES ALLWAYS_REGISTROS(ID),
    CONSTRAINT FK_CUP_PART FOREIGN KEY (PARTICIPANTE_ID) REFERENCES ALLWAYS_PARTICIPANTES(ID)
);

-- 5. ALLWAYS_PREMIOS
CREATE TABLE ALLWAYS_PREMIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MES VARCHAR2(20) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    IMAGEN VARCHAR2(500),
    CUPON_GANADOR_ID NUMBER,
    FECHA_SORTEO DATE,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT FK_PREMIO_CUPON FOREIGN KEY (CUPON_GANADOR_ID) REFERENCES ALLWAYS_CUPONES(ID)
);

-- 6. ALLWAYS_ADMIN_LOG
CREATE TABLE ALLWAYS_ADMIN_LOG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ADMIN_ID NUMBER,
    ACCION VARCHAR2(100),
    DETALLE VARCHAR2(500),
    IP VARCHAR2(45),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOG_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ALLWAYS_ADMIN(ID)
);
