-- ============================================================
-- Allways Show de Premios - Index Creation Script
-- Oracle 19C
-- ============================================================

CREATE INDEX IDX_REG_PARTICIPANTE ON ALLWAYS_REGISTROS(PARTICIPANTE_ID);
CREATE INDEX IDX_REG_ESTADO ON ALLWAYS_REGISTROS(ESTADO);
CREATE INDEX IDX_REG_FECHA ON ALLWAYS_REGISTROS(FECHA_REGISTRO);
CREATE INDEX IDX_CUP_PARTICIPANTE ON ALLWAYS_CUPONES(PARTICIPANTE_ID);
CREATE INDEX IDX_CUP_NUMERO ON ALLWAYS_CUPONES(NUMERO_CUPON);
CREATE INDEX IDX_PART_CEDULA ON ALLWAYS_PARTICIPANTES(CEDULA);
